spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory_service
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8082 # You can choose a different port for the inventory service

logging:
  level:
    root: INFO # Adjust log level as needed

# Other application-specific configurations
