app:
  application-name: inventory-service
  server-port: 8083
  #  server-port: 0
  eureka-hostname: localhost
  eureka-port: 8761
  database-hostname: localhost
  database-port: 5434
  database-name: inventory_service
  kafka-hostname: localhost
  kafka-port: 9092
  kafka-default-topic: notificationTopic
  kafka-concurrency: 3
  context-path: api/inventory

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-hostname}:${app.eureka-port}/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0
    locations: classpath:db/migration/
    validate-on-migrate: true
    enabled: true
    table: schema_history
  application:
    name: ${app.application-name}
  datasource:
    url: jdbc:postgresql://${app.database-hostname}:${app.database-port}/${app.database-name}
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    enabled: true
    bootstrap-servers: ${app.kafka-hostname}:${app.kafka-port}
    template:
      default-topic: ${app.kafka-default-topic}
    producers:
      order-item-not-available:
        topic-name: order-item-not-available
      order-processing:
        topic-name: order-processing
    consumers:
      order-pending:
        topic-name: order-pending
        group-id: order-pending-${app.application-name}
        properties:
          concurrency: ${app.kafka-concurrency}

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: ${app.server-port}
  servlet:
    context-path: /${app.context-path}

logging:
  level:
    root: INFO
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"